require: rubocop-rspec

AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true
  NewCops: enable
  TargetRubyVersion: 3.0
  Exclude:
    - "bin/*"
    - Capfile
    - config/boot.rb
    - config/environment.rb
    - db/schema.rb
    - "node_modules/**/*"
    - "tmp/**/*"
    - "vendor/**/*"
    - Gemfile
    - Rakefile

Style/Documentation:
  Enabled: false

Layout/IndentationConsistency:
  EnforcedStyle: indented_internal_methods

Layout/LineLength:
  Exclude:
    - "config/**/*"
    - "db/**/*"

Metrics/BlockLength:
  Exclude:
    - "config/**/*"
    - "spec/**/*"

Metrics/ClassLength:
  Exclude:
    - "spec/**/*"
